### ISSUE TITLE
Create Learning Objectives

### ISSUE THREAD

**Issue by Racel** [DynamoDS/DynamoWorkshops#1]
We need consistent learning objectives across all the breakout sessions. We should define what those objectives should be in this task.

------
Potential learning objectives

- Able to build Dynamo Core
- Able to create, build, and run a view extension

**Comment by radumg** [comment]
for the `create a view extension` learning objective, i'd suggest we define some further concrete outcomes :

- [x] create a new menu item that runs a Dynamo command without a UI (add a node to canvas ?) 
- [x] react to a Dynamo event
- [ ] something else ?

**Comment by andydandy74** [comment]
@Racel @radumg Can we close this?

**Comment by radumg** [comment]
Yep 👍 

Typed on a tiny screen
