### ISSUE TITLE
Determine Forum Presentation format

### ISSUE THREAD

**Issue by Racel** [DynamoDS/DynamoWorkshops#2]
Each breakout session is responsible for delivering a presentation at the computational bim forum following the workshop.

Collectively we have 20 minutes.

Let's decide on the format of this.

**Comment by andydandy74** [comment]
@johnpierson / @Racel - Can you close this once the boilerplate slide decks for each session are up on GDrive?

**Comment by johnpierson** [comment]
I have them up right now all compiled as one. Do you want me to split them into each session?

**Comment by andydandy74** [comment]
Would perhaps make sense so everybody can edit their bit separately without accidentally overwriting someone else's stuff.

**Comment by johnpierson** [comment]
Cool! this is done. I went ahead and named the presentations based on what AU listed on the speaker portal for the requirement.

**Comment by radumg** [comment]
Legend ! 👏

Typed on a tiny screen
