### ISSUE TITLE
debugging is specific to Eric's machine

### ISSUE THREAD

**Issue by radumg** [DynamoDS/DynamoWorkshops#8]
the `Install Extensions - DEBUG.bat` script references locations on @wynged 's machine.

we should exchange this with `post-build` steps so that all participants can debug without having to configure anything.

**Comment by wynged** [comment]
Yea, this is definitely bad, sorry all!  Should we simplify and maybe just have one install script?  How have others been debugging their extensions?  another option for debugging would be to have a special debug xml file that the user customizes to their own machine, which points to the debug build location in the project.  Thoughts?

**Comment by radumg** [comment]
@teocomi and I have been adding those `xcopy` instructions in the `post-build` steps of the project and point the `start external application` setting in `Debug` to the `DynamoSandbox.exe`. This way, you just press the green `Start` button and a fresh copy of the extension is deployed and Dynamo started.

@teocomi has a PR open that makes this change #10

**Comment by radumg** [comment]
fixed in #10
